apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myserver2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: myserver2
    spec:
      containers:
      - name: main
        command: ["/bin/bash", "-c", "while true ; do date ; sleep 1 ; done"]
